import React, { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeftRight, CarFront, Check, CircleOff, CloudRain, Construction, LightbulbOff, LockKeyhole, MapPin, MapPinned, PawPrint, Radio, Siren, TrafficCone, Trash2, Waves, X } from 'lucide-react';
import { IncidentReport, IncidentType } from '../types';
import { hapticSuccess, hapticTick } from '../utils/haptics';

interface IncidentReporterProps { onReport: (type: IncidentType, details?: string) => void; onClose: () => void; theme?: 'light' | 'dark'; isMobile?: boolean; activeIncidents?: IncidentReport[]; onRemoveIncident?: (id: string) => void; currentUserId?: string; }
type Icon = React.ComponentType<{ className?: string }>;
interface ReportChoice { label: string; details: string; icon: Icon; type?: IncidentType; }
interface ReportCategory { id: string; type: IncidentType; label: string; sublabel: string; icon: Icon; color: string; choices: ReportChoice[]; permanent?: boolean; }

const CATEGORIES: ReportCategory[] = [
  { id: 'crash', type: 'crash', label: 'Crash', sublabel: 'Collision ahead', icon: AlertTriangle, color: 'rose', choices: [{ label: 'Crash', details: 'Crash', icon: AlertTriangle }, { label: 'Multi-vehicle', details: 'Multi-vehicle crash', icon: CarFront }, { label: 'Other side', details: 'Crash on the other side', icon: ArrowLeftRight }] },
  { id: 'traffic', type: 'traffic', label: 'Traffic', sublabel: 'Slow or stopped', icon: TrafficCone, color: 'red', choices: [{ label: 'Traffic', details: 'Moderate traffic', icon: TrafficCone }, { label: 'Heavy', details: 'Heavy traffic', icon: CarFront }, { label: 'Standstill', details: 'Standstill traffic', icon: CircleOff }] },
  { id: 'hazard', type: 'hazard', label: 'Hazard', sublabel: 'Object or danger', icon: AlertTriangle, color: 'amber', choices: [{ label: 'Road hazard', details: 'Road hazard', icon: AlertTriangle }, { label: 'Debris', details: 'Debris in road', icon: Construction }, { label: 'Vehicle on shoulder', details: 'Stopped vehicle on shoulder', icon: CarFront, type: 'shoulder' }] },
  { id: 'blocked-lane', type: 'blocked_lane', label: 'Blocked lane', sublabel: 'Lane obstruction', icon: TrafficCone, color: 'orange', choices: [{ label: 'Any lane', details: 'Blocked lane', icon: TrafficCone }, { label: 'Left lane', details: 'Left lane blocked', icon: ArrowLeftRight }, { label: 'Center lane', details: 'Center lane blocked', icon: TrafficCone }, { label: 'Right lane', details: 'Right lane blocked', icon: ArrowLeftRight }] },
  { id: 'weather', type: 'bad_weather', label: 'Bad weather', sublabel: 'Road conditions', icon: CloudRain, color: 'sky', choices: [{ label: 'Rain', details: 'Heavy rain', icon: CloudRain }, { label: 'Fog', details: 'Low visibility fog', icon: CloudRain }, { label: 'Icy road', details: 'Icy road', icon: AlertTriangle }, { label: 'Flooding', details: 'Flooded road', icon: Waves }] },
  { id: 'animal', type: 'animal', label: 'Animal', sublabel: 'On or near road', icon: PawPrint, color: 'emerald', choices: [{ label: 'Animal', details: 'Animal near road', icon: PawPrint }, { label: 'In lane', details: 'Animal in lane', icon: PawPrint }, { label: 'On shoulder', details: 'Animal on shoulder', icon: PawPrint }] },
  { id: 'closure', type: 'road_closed', label: 'Road closed', sublabel: 'Blocked or detour', icon: CircleOff, color: 'violet', choices: [{ label: 'Road closed', details: 'Road closed', icon: CircleOff }, { label: 'Construction', details: 'Construction closure', icon: Construction, type: 'construction' }, { label: 'Signal out', details: 'Traffic signal out', icon: LightbulbOff, type: 'signal_out' }] },
  { id: 'access', type: 'missing_vehicle_access', label: 'Map & access', sublabel: 'Lasting map correction', icon: MapPinned, color: 'indigo', permanent: true, choices: [{ label: 'Missing vehicle access', details: 'Missing vehicle access', icon: MapPinned }, { label: 'Wrong direction', details: 'Wrong traffic direction', icon: ArrowLeftRight, type: 'wrong_traffic_direction' }, { label: 'Restricted access', details: 'Private or restricted access', icon: LockKeyhole, type: 'restricted_access' }] },
];
const colorClasses: Record<string, string> = { rose: 'border-rose-400 bg-rose-500/15 text-rose-800 dark:text-rose-100', red: 'border-red-400 bg-red-500/15 text-red-800 dark:text-red-100', amber: 'border-amber-400 bg-amber-500/15 text-amber-800 dark:text-amber-100', orange: 'border-orange-400 bg-orange-500/15 text-orange-800 dark:text-orange-100', sky: 'border-sky-400 bg-sky-500/15 text-sky-800 dark:text-sky-100', emerald: 'border-emerald-400 bg-emerald-500/15 text-emerald-800 dark:text-emerald-100', violet: 'border-violet-400 bg-violet-500/15 text-violet-800 dark:text-violet-100', indigo: 'border-indigo-400 bg-indigo-500/15 text-indigo-800 dark:text-indigo-100' };
const lightTextColors: Record<string, string> = { rose: '#9f1239', red: '#991b1b', amber: '#92400e', orange: '#9a3412', sky: '#075985', emerald: '#065f46', violet: '#5b21b6', indigo: '#3730a3' };
const iconForType = (type: IncidentType): Icon => CATEGORIES.find(category => category.type === type)?.icon || AlertTriangle;

const IncidentReporter: React.FC<IncidentReporterProps> = ({ onReport, onClose, theme = 'dark', activeIncidents = [], onRemoveIncident }) => {
  const [category, setCategory] = useState<ReportCategory | null>(null);
  const [choice, setChoice] = useState<ReportChoice | null>(null);
  const [selectingCategoryId, setSelectingCategoryId] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const isDark = theme === 'dark';
  const selectableChoices = useMemo(() => category?.choices || [], [category]);
  const selectCategory = (next: ReportCategory) => {
    if (selectingCategoryId) return;
    hapticTick();
    setSelectingCategoryId(next.id);
    window.setTimeout(() => {
      setCategory(next);
      setChoice(null);
      setSelectingCategoryId(null);
    }, 140);
  };
  const submit = () => { if (!category || !choice) return; hapticSuccess(); onReport(choice.type || category.type, choice.details); setSubmitted(true); window.setTimeout(onClose, 1100); };
  const back = () => choice ? setChoice(null) : setCategory(null);
  const title = submitted ? 'Report shared' : choice ? `Report ${category?.label.toLowerCase()}` : category ? `Report ${category.label.toLowerCase()}` : 'Report road condition';
  return <div className="fixed inset-0 z-[150] flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/75 backdrop-blur-md animate-in fade-in duration-200 pointer-events-auto">
    <div className={`w-full max-w-lg rounded-t-[2rem] sm:rounded-3xl p-5 sm:p-6 shadow-2xl border relative overflow-hidden max-h-[88vh] flex flex-col ${isDark ? 'bg-slate-900/98 border-white/15 text-white' : 'bg-white/98 border-slate-200 text-slate-900'}`}>
      <div className="flex items-center justify-between mb-4 shrink-0"><div className="flex items-center gap-2.5"><div className="w-9 h-9 rounded-2xl bg-gradient-to-tr from-amber-500 to-orange-500 flex items-center justify-center shadow-lg"><Radio className="w-5 h-5 text-white" /></div><div><h3 className="text-base font-black tracking-tight">{title}</h3><p className="text-[11px] font-bold text-slate-400">{choice ? 'Review, then share this report.' : category ? 'Choose the most accurate option.' : 'Choose a category, then confirm it.'}</p></div></div><button onClick={onClose} aria-label="Close report menu" className="w-9 h-9 rounded-full bg-white/10 hover:bg-white/20 text-slate-400 hover:text-white flex items-center justify-center cursor-pointer"><X className="w-5 h-5" /></button></div>
      <div className="flex-1 overflow-y-auto no-scrollbar">
        {submitted ? <div className="py-10 flex flex-col items-center justify-center gap-3"><div className="w-16 h-16 rounded-full bg-emerald-500/20 border-2 border-emerald-400 flex items-center justify-center"><Check className="w-8 h-8 text-emerald-300" /></div><h4 className="text-lg font-black">Report shared</h4><p className="text-xs text-emerald-400 font-bold">Drivers nearby can confirm or clear it.</p></div> : !category ? <div className="grid grid-cols-2 gap-3">{CATEGORIES.map(item => { const Icon = item.icon; const isSelecting = selectingCategoryId === item.id; return <button key={item.id} type="button" onClick={() => selectCategory(item)} aria-pressed={isSelecting} style={{ color: isDark ? '#f8fafc' : lightTextColors[item.color] }} className={`min-h-28 rounded-2xl border p-3 flex flex-col items-center justify-center gap-2 transition-all cursor-pointer ${isSelecting ? 'scale-[.97] ring-4 ring-cyan-400/60 shadow-lg' : 'active:scale-[.98]'} ${colorClasses[item.color]}`}><div className={`relative ${isSelecting ? 'scale-90' : ''}`}><Icon className="w-7 h-7" />{isSelecting && <Check className="absolute -right-4 -top-3 w-4 h-4 rounded-full bg-cyan-400 text-slate-950 p-0.5" />}</div><div className="text-center"><p className="text-xs font-black leading-tight">{item.label}</p><p className="text-[9px] font-bold opacity-70 mt-0.5">{item.sublabel}</p></div></button>; })}</div> : !choice ? <div className="space-y-3">{selectableChoices.map(item => { const Icon = item.icon; return <button key={item.details} type="button" onClick={() => { hapticTick(); setChoice(item); }} className="w-full min-h-16 rounded-2xl border border-white/15 bg-white/5 hover:bg-white/10 p-3.5 flex items-center gap-3 text-left active:scale-[.99] cursor-pointer"><div style={{ color: isDark ? '#f8fafc' : lightTextColors[category.color] }} className={`w-10 h-10 rounded-xl flex items-center justify-center ${colorClasses[category.color]}`}><Icon className="w-5 h-5" /></div><span className="font-black text-sm flex-1">{item.label}</span><span className="text-slate-400 text-lg">›</span></button>; })}</div> : <div className="space-y-4"><div style={{ color: isDark ? '#f8fafc' : lightTextColors[category.color] }} className={`rounded-2xl border-2 p-5 text-center ${colorClasses[category.color]}`}><div className="w-12 h-12 mx-auto rounded-2xl bg-black/15 flex items-center justify-center mb-3">{React.createElement(choice.icon, { className: 'w-7 h-7' })}</div><p className="text-lg font-black">{choice.label}</p><p className="text-xs font-bold opacity-80 mt-1">This will be shared with drivers near this location.</p></div><p className="px-2 text-center text-[11px] font-bold text-slate-400">{category.permanent ? 'This correction stays on the map until the community removes it.' : 'Reports expire automatically unless drivers keep confirming them.'}</p></div>}
        {activeIncidents.length > 0 && onRemoveIncident && !category && <div className="pt-5 mt-5 border-t border-white/10 space-y-2"><p className="text-[10px] font-black uppercase tracking-wider text-amber-400">Active reports ({activeIncidents.length})</p><div className="space-y-1.5 max-h-32 overflow-y-auto no-scrollbar">{activeIncidents.map(inc => { const Icon = iconForType(inc.type); return <div key={inc.id} className="p-2.5 rounded-xl bg-white/5 border border-white/10 flex items-center justify-between gap-2"><div className="flex items-center gap-2 min-w-0"><Icon className="w-5 h-5 text-amber-300 shrink-0" /><p className="text-xs font-black capitalize truncate">{inc.details || inc.type.replace(/_/g, ' ')}</p></div><button type="button" onClick={() => onRemoveIncident(inc.id)} className="p-2 rounded-lg bg-rose-600/80 text-white active:scale-95 cursor-pointer" aria-label="Remove report"><Trash2 className="w-3.5 h-3.5" /></button></div>; })}</div></div>}
      </div>
      {!submitted && <div className="mt-4 pt-3 border-t border-white/10 flex gap-3 shrink-0">{category ? <button type="button" onClick={back} className="flex-1 min-h-12 rounded-xl border border-white/15 font-black text-sm text-slate-300 hover:bg-white/5 cursor-pointer">Back</button> : <button type="button" onClick={onClose} className="flex-1 min-h-12 rounded-xl border border-white/15 font-black text-sm text-slate-300 hover:bg-white/5 cursor-pointer">Cancel</button>}{choice && <button type="button" onClick={submit} className="flex-[1.4] min-h-12 rounded-xl bg-cyan-400 hover:bg-cyan-300 text-slate-950 font-black text-sm cursor-pointer shadow-lg">Report</button>}</div>}
      {!category && <div className="mt-3 flex items-center justify-center gap-1 text-[10px] text-slate-400 font-bold shrink-0"><MapPin className="w-3 h-3" /> Uses current GPS coordinates</div>}
    </div>
  </div>;
};
export default IncidentReporter;
